import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Validation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <form>
          <label htmlFor="firstName">First Name</label>
          <input type="text" name="firstName" />
          <label htmlFor="lastName">Last Name</label>
          <input type="text" name="firstName" />
          <label htmlFor="firstName">Email</label>
          <input type="text" name="email" />
          <label htmlFor="age">Age</label>
          <input type="text" name="age" />
          <label htmlFor="age">Password</label>
          <input type="text" name="password" />
          <label htmlFor="age">Confirm Password</label>
          <input type="text" name="confirmPassword" />
        </form>
      </div>
    </div>
  );
};

export default Home;
